### ISSUE TITLE
TODO List for release 0.6.0

### ISSUE THREAD

**Issue by corka149** [pytogo/portforward#20]
TODO List for the upcoming release 0.6.0:

- [x]  Error handling (Remove unwraps, introduce err-return mechanism)
- [x] Forward to either pod or service
- [x] Context strategy (use default context when no context was provided)
- [x] Determining kube config (Use path > use $HOME/.kube/config > use incluster-config)
- [x] Integration tests
- [x] CI (github actions with runing K8s)
- [x] Publishing (setup.py was removed - use pyproject.toml instead)
- [x] Allow multiple port-forwards to same pod or service

**Comment by corka149** [comment]
The switch to Rust is postponed for now.
